export const typePrompt = [
  "Crypto",
  "Business",
  "Programmation",
  "Apprentissage",
  "Image",
  "Proverbe",
  "Ecrivain",
  "Marketing",
  "Artiste&Designer",
  "Personnel",
  "Scientifique",
  "Réseaux Sociaux",
  "Ai Art",
];

export const prompts = {
  Crypto: [
    "Quel est l'utilité de la crypto?",
    "C'est quoi un crypto?",
    "Comment puis-je me lancer dans la crypto monnaie?",
  ],
  Business: [
    "Quel genre de business puis-je lancer en tant qu'étudiant?",
    "Quel sont les business les plus rentables?",
    "Quel business lancer quand je n'ai pas de capital?",
  ],
  Programmation: [
    "C'est quoi la programmation?",
    "Est-il possible de commancer la programmation à mon âge?",
    "Quel sont les platfomes que je peux utilisé pour apprendre la programmation?",
  ],
  Apprentissage: [
    "Quel sont les métiers que je peux apprendre en tant qu'etudiant?",
    "Est-ce que tu peux m'apprendre l'anglais?",
    "Comment faire pour apprendre plus vite?",
  ],
  Image: [
    "A cat in space",
    "A cat that draw the portrait of another cat",
    "A village",
  ],
  Proverbe: [
    "Donne moi un proverbe aléatoire mais populaire",
    "Quel proverbe parle d'un SDF qui demande de l'aide à un homme riche",
    "Crée un proverbe de ton choix",
  ],
  Ecrivain: [
    "Écrivez une courte histoire sur un détective qui voyage dans le temps",
    "Créez un dialogue entre deux personnages de siècles différents",
    "Développez une esquisse de personnage pour un héros doté d'un super pouvoir inhabituel",
    "Rédigez un article de fond sur l’impact des médias sociaux sur la créativité",
    "Créez une histoire pour un méchant qui incite le public à sympathiser avec lui",
    "Rédigez une critique d’un livre de fiction qui n’a pas encore été écrit",
  ],
  Marketing: [
    "Rédigez une description de produit attrayante pour une bouteille d’eau écologique",
    "Concevez une campagne sur les réseaux sociaux pour une agence de voyage en réalité virtuelle",
    "Créez une ligne d'objet d'e-mail convaincante pour une vente de vacances",
    "Générez une liste de mots-clés SEO pour une agence de marketing numérique",
  ],
  "Artiste&Designer": [
    "Générez une idée de fresque murale qui célèbre la diversité communautaire.",
    "Fournissez une invite pour une œuvre d’art abstrait qui explore le thème de la « connexion ».",
    "Générer un concept pour une ligne de mode inspirée des écosystèmes sous-marins.",
    "Suggérez une scène de paysage à générer par une IA avec une cascade cachée",
    "Inventez un design de personnage pour un jeu vidéo se déroulant dans l’espace.",
  ],
  Personnel: [
    "Développez une invite de journal explorant le concept de gratitude.",
    "Rédigez une invite de réflexion sur les réalisations en matière de croissance personnelle au cours de la dernière année.",
    "Générez une liste de citations de motivation pour surmonter les défis",
    "Créez un exercice de pleine conscience axé sur la conscience de la respiration.",
    "Décrire une stratégie pour améliorer les compétences en gestion du temps.",
    "Créez un défi de déconnexion des appareils numériques pendant 24 heures.",
    "Générez des invites pour un projet de rédaction de lettres à votre futur moi",
  ],
  Scientifique: [
    "Expliquez le processus de la photosynthèse en termes simples.",
    "Décrire les impacts potentiels de l’IA sur les soins de santé",
    "Développez un didacticiel sur la création d’une application mobile simple",
    "Expliquez l'importance des découvertes du télescope spatial James Webb",
    "Rédigez un guide d'introduction au piratage éthique pour les passionnés de cybersécurité.",
    "Rédiger un rapport sur l’avenir des technologies de transport.",
  ],
  "Réseaux Sociaux": [
    "Créez un tweet engageant sur l’importance du vote.",
    "Rédigez un article LinkedIn sur des conseils de réseautage pour les jeunes professionnels.",
    "Créez une idée de défi TikTok accrocheuse promouvant la sensibilisation à l'environnement.",
    "Développez une publication Facebook sensibilisant à l’adoption d’animaux.",
    "Créez un script TikTok encourageant les gens à essayer de nouveaux passe-temps",
  ],
  "Ai Art": [
    "A serene landscape depicting the harmony between technology and nature",
    "A vibrant city at night, illuminated by neon lights and bustling with life.",
    "A surreal depiction of time travel, blending historical and futuristic elements.",
    "An abstract representation of emotions, using bold colors and dynamic shapes.",
    "A portrait of an ancient civilization thriving on Mars.",
    "A whimsical forest filled with bioluminescent plants and animals.",
    "The bustling streets of a futuristic city designed with sustainability in mind.",
    "A dynamic scene capturing the energy of a music festival.",
  ],
};
